# Generated by Django 3.2.18 on 2023-05-23 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='restaurants',
            field=models.ManyToManyField(related_name='roles', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_functions', to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobfunction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_functions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobfunction_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='dine_up_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='accounts.dineupuser'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurants',
            field=models.ManyToManyField(related_name='employees', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dineupuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dineupuser_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dineupuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dineupuser_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dineupuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobfunction',
            unique_together={('employee', 'branch')},
        ),
    ]
